# Generated by Django 4.2.1 on 2023-06-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0004_nuevo_producto_imgproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevo_producto',
            name='descProducto',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
