# Generated by Django 4.2.1 on 2023-06-08 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0013_matchpublicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpublicacion',
            name='match_tipoTrans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_DUOC_Swap_django.tipotrans'),
        ),
    ]
