# Generated by Django 4.2.1 on 2023-06-08 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0014_matchpublicacion_match_tipotrans'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='categoriaTags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_DUOC_Swap_django.categoria'),
        ),
        migrations.DeleteModel(
            name='MatchPublicacion',
        ),
    ]
