# Generated by Django 4.2.1 on 2023-06-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0016_alter_tags_nombretags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevoproducto',
            name='p_tags',
        ),
        migrations.AddField(
            model_name='nuevoproducto',
            name='p_tags',
            field=models.ManyToManyField(to='app_DUOC_Swap_django.tags'),
        ),
    ]
