# Generated by Django 4.2.1 on 2023-06-11 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0018_remove_nuevoproducto_p_tags_nuevoproducto_p_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchProductoRegalo',
            fields=[
                ('mpregalo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_propuesta', models.DateTimeField(auto_now_add=True)),
                ('estado_solicitud', models.IntegerField(choices=[(0, 'Sin Confirmación'), (1, 'Confirmado')])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_DUOC_Swap_django.nuevoproducto')),
                ('usuario_dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_dueno', to='app_DUOC_Swap_django.nuevoproducto')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_solicitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
