# Generated by Django 4.2.1 on 2023-06-11 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0023_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='PostMatch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_DUOC_Swap_django.matchproductoregalo'),
        ),
    ]
