# Generated by Django 4.2.1 on 2023-06-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0024_mensajes_postmatch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='PostMatch_id',
            new_name='PostMatch',
        ),
    ]
