# Generated by Django 4.2.1 on 2023-06-13 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0026_rename_mpregalo_id_matchproductoregalo_postmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchProductoCambio',
            fields=[
                ('PostMatch', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_propuesta', models.DateTimeField(auto_now_add=True)),
                ('estado_solicitud', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('confirmacion_match', models.IntegerField(choices=[(0, 'No confirmado'), (1, 'Confirmado')], default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_DUOC_Swap_django.nuevoproducto')),
                ('producto_propuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_propuesto', to='app_DUOC_Swap_django.nuevoproducto')),
                ('usuario_dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_cambio_dueno', to='app_DUOC_Swap_django.nuevoproducto')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_cambio_solicitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
