# Generated by Django 4.2.1 on 2023-06-14 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0029_nuevoproducto_p_habilitar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchproductoregalo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_producto', to='app_DUOC_Swap_django.nuevoproducto'),
        ),
        migrations.AlterField(
            model_name='matchproductoregalo',
            name='usuario_dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_dueno', to=settings.AUTH_USER_MODEL),
        ),
    ]
