# Generated by Django 4.2.1 on 2023-06-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0002_categoria_tags_tipotrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nuevo_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePublicacion', models.CharField(max_length=60)),
            ],
        ),
    ]
