# Generated by Django 4.2.1 on 2023-06-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0003_nuevo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevo_producto',
            name='imgProducto',
            field=models.ImageField(null=True, upload_to='img/imgUploadProducto'),
        ),
    ]
