# Generated by Django 4.2.1 on 2023-06-03 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0007_rename_descproducto_nuevo_producto_p_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevo_producto',
            name='p_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_DUOC_Swap_django.categoria'),
        ),
        migrations.AddField(
            model_name='nuevo_producto',
            name='p_tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_DUOC_Swap_django.tags'),
        ),
    ]
