# Generated by Django 4.2.1 on 2023-06-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0008_nuevo_producto_p_categoria_nuevo_producto_p_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nuevo_Producto',
            new_name='NuevoProducto',
        ),
    ]
