# Generated by Django 4.2.1 on 2023-06-03 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0009_rename_nuevo_producto_nuevoproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_DUOC_Swap_django.nuevoproducto')),
                ('tagPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_DUOC_Swap_django.tags')),
            ],
        ),
    ]
