# Generated by Django 4.2.1 on 2023-06-03 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0010_tagspublicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevoproducto',
            name='p_account_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
