# Generated by Django 4.2.1 on 2023-06-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0012_tablaprueba_alter_nuevoproducto_p_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmMatch', models.BooleanField(default=False)),
            ],
        ),
    ]
