# Generated by Django 4.2.1 on 2023-06-08 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0017_remove_nuevoproducto_p_tags_nuevoproducto_p_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevoproducto',
            name='p_tags',
        ),
        migrations.AddField(
            model_name='nuevoproducto',
            name='p_tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_DUOC_Swap_django.tags'),
        ),
    ]
