# Generated by Django 4.2.1 on 2023-06-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0019_matchproductoregalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchproductoregalo',
            name='estado_confirmacion',
            field=models.IntegerField(choices=[(0, 'Sin Confirmación'), (1, 'Confirmado')], default=0),
        ),
        migrations.AlterField(
            model_name='matchproductoregalo',
            name='estado_solicitud',
            field=models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1),
        ),
    ]
