# Generated by Django 4.2.1 on 2023-06-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0020_matchproductoregalo_estado_confirmacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchproductoregalo',
            name='confirmacion_match',
            field=models.IntegerField(choices=[(0, 'No confirmado'), (1, 'Confirmado')], default=0),
        ),
    ]
