# Generated by Django 4.2.1 on 2023-06-11 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0021_matchproductoregalo_confirmacion_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchproductoregalo',
            name='estado_confirmacion',
        ),
    ]
