# Generated by Django 4.2.1 on 2023-06-11 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0022_remove_matchproductoregalo_estado_confirmacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensajePost', models.TextField()),
                ('usuarioPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posteos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
