# Generated by Django 4.2.1 on 2023-06-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0025_rename_postmatch_id_mensajes_postmatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchproductoregalo',
            old_name='mpregalo_id',
            new_name='PostMatch',
        ),
    ]
