# Generated by Django 4.2.1 on 2023-06-14 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DUOC_Swap_django', '0031_alter_matchproductocambio_producto_propuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchproductocambio',
            name='producto_propuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_propuesto', to='app_DUOC_Swap_django.nuevoproducto'),
        ),
        migrations.AlterField(
            model_name='matchproductocambio',
            name='usuario_dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_cambio_dueno', to=settings.AUTH_USER_MODEL),
        ),
    ]
